version: '3.3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}
  fermentrack_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: fermentrack_django
    depends_on:
      - postgres
      - redis
    volumes:
      - /dev:/dev
      - fermentrack_data:/app/data:Z
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    ports:
      - "0.0.0.0:8123:8123"
    command: ["/start", "--privileged"]
    privileged: true
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: fermentrack_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    restart: unless-stopped

  redis:
    image: redis:5.0
    restart: unless-stopped
